name: Build LLVM Obfuscator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository (your fork)
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          ref: llvm-4.0

    # Step 2: Install dependencies (CMake, GCC, Clang, etc.)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git ninja-build

    # Step 3: Create a build directory
    - name: Create build directory
      run: mkdir -p build

    # Step 4: Configure CMake and build LLVM with obfuscator
    - name: Configure CMake
      working-directory: build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release ../
        make -j$(nproc)

    # Step 5: Verify the build (optional)
    - name: Verify build
      working-directory: build
      run: |
        ./bin/clang --version

    # Step 6: Upload build artifacts using the latest action version
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: obfuscator-build
        path: build/bin/
